language: node_js
node_js:
- 0.12.7
services:
- mongodb
before_install:
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: nFj7Fuzgq9VAcVYSrpkcnmZz0J4xYMkp4Ug2g681VyBsO/eeS1DcN0TrYZG/raqesjUag9y6+fV9WRiJhhSqHGczYOcLjWiN/qYjwcMrjOLI/m2+bJgbdDnCBYXQyz10LisAPNmSaVdZp8WQxkkPUJYvGff7x4NRFfxj9EeCYI6OIbZ2QPeS8cpJDOA4DIL19hfzgzwkMjEK212c6TRtR/qYyXqsDH9NrZcvk3FBbFFSCcEZ9MgUKfqPFOCdvl51wo1Zm/A3QFkiOZx+tJSI0GqKHq5gGBtQ2v9YpJ7lbeZTjJjJWV/qX8EXiXd8LsCMbN9f9EeN32imMDixW00xBlwupPYBPADL0CeAgXv7jPon9cM0vEzaFXB/W59N8ZwCx4YFCUstwU/6WYSztfNyNRh5X5ErUbduyraF9TyDyLjUhWVHKj8vS7fRF0mIdKGArcGrYMTB8W7xVhq7oT5r7FScUSPl9RoHaErLZiMvB9B4fhkhxVmCmLLtsqha/JbGK7AqgkFhpI9ZYll6H+s9puZYeO8DlDSF98CPke0zloer8IQRxWtqg/eccRcJmQezv4hZE41PmZohxSShdlDJMP05w4kLvhIgzHWuev8kOaQjLNByPeuJYQODh/Vf0duLc+PLVNEC+Fae/PdwcWsmweF1BYkPMgIaj1JRj+9MDpc=
  app: habit-trainer
  on:
    repo: greenfield-apollo/greenfield-apollo
    branch: staging
env:
  global:
  - secure: SOj+MbZ4In5dbl8MLZ9TRnZ12sc6KHtqKtzY+RY2gMoQfO9YMz+VW7D/WC3Xgl/GAuJ86a8680yG6mk42jrR5pL0eVlzIUH2cekNkyx4mGswhSMac0skrUKGAiM/G60XUxm5sMSbr6mgKxVuA4clCVabr/v15C/1zFKzE/gQdJFJzBhnYxI2UfU0dg9nfv4dp/8YqKQe3pCX6pFKDP5LPrBpIhYZ9pm5sSN5sXB6sSXsMxijE2ybcGVFt+UNZgMVlQmSulclEa+Ya679dEwsgmrzzTIKOeV86YXfZgxSQ5lRQvqVb996+w3XFahvPoUUCN9j1oIReJLvo1anrZ/+hkaSEYQK1KDqigEXHcWtVMeh8nwsOHMG84lAR/Hu5p65oo64nNx7MH97S86CrHikxdRYQWohcfqXVDn6hZMq+HfCKwN3U3pdPDK27xRMxBigi+H854ei11X4RQwfaffWWt496vdui0KKzQGrLEl88IawM0ic3tyfp/JdZfXaLGnIIufRRRE7NnjBNwIdEq5V8OEBFiZDzeqPXSB5fhH5AlcbXpvyAUNuIVDGgs9HLsZi7OQdUTlAuoTUx8vTh/IrqNdKTlY0WZXaiEXXHhtc9GpE27aPDvT6FnCsGZzDLzDpmlyr5lMFDPHDlrpFIRII/3vtRF8zcRD6xm40SUDlDt8=
  - secure: tOfBPiEX1dOtfSbqFjDb9wTkImVv+AnLF2aqoklQXUlCKfVIGx2B/UC1871xSXPEwREtGYu6jtVOD8qTe5XhJqf11TUt7pUhEbcu2uEAYyDe+fifKd3VYXE8e9aLymES7qRLv4bsprL95SGVGa1Z8r3Y16GjyUf3HPw71hMbuFlTVyyzKOg+Xx2m9o4xwMvC8oyeKsvvcPdbIxv6IfwrjdwZDq5hlYInpGB7unoLMp03uOmJeBMW73ZfP05O0GBp6iYd5CMyZynv7S9clzt2WVhdz4lXWWICwTiAhg+4hV67FNqYoijR8pkt3j+4tjhDmrYVD3xQocimewa4RF7MvMlJAHT1QmnWyljwXaywsPWWWv7vwyNc81/HXk6vercBdmNKArehZsNLGfceOVHOKisPunplI0WvdzLBCAI/cXO4LiYs+FydkJCLqMkRU81fq9EZz1tWJ15F7FgE3jGEFbg6nXO5+66Tbl/15uDfKZDzhrAD6jexEvk4en79xUqcVEOaklcYeGp8v+uEw8HMcGJdF81ZRqwd4Kjey7ar9Gq2nVFiHjlcvEkD9bGfqOCbiyK1MP9zmMWw96k+/3FiBPMi++EKP+xv3QnMOImXv0jmgX2yszrlTpJ891wLGwvutN7ZvNsgg+4ttbU1mU0FkqUxBil8fazjAOX4cH0o+Ng=
