language: node_js
node_js:
- 0.12.7
services:
- mongodb
before_install:
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: paC3p9ZwtkKkq325wM3CE3gczV98ulSQQPzaoVZJCw/EicyYxiBFMO42MF5OZNABluDRVMDI1lStuSGUVBKaGhRD9Op+oAqSB4mwDo72QofTmoQnRspA0LinEJjndC7DwLjmSi2gohhA0G9B2WhCOy8XSSP6dcJpvE+XlyqJQFkebJREsBqwbDQu0m0yX2FRGuIxGTkKJdXSzCYstb7plVzR1zgzozR56yM5Q9T4+YL7BuY1D0BNqkbHgsvxoooGitv5iWxqpazbO78opGjOl0zwj4MO2s4jPhQxxz/kTxF3N2waUTKzEYktOSufe6WGCRCGl4A32WmuQ75l2EBFh84cvQFK+CQ8bgw9nZATSJFimhxppp2NShfo6AivGe8Jixvy5BBADBD1jXaolGtMgahfuuDYCI8eaWubFxzJCEcQqrDjq/aDxwx6fySfdeq02bHKo0WDTw01rg6ePHNC1IracDiE1OteFUT5BrI1opWEUQqanPXVurEGxmRIJgkvWlhjlczkIOWy7l0nuoLJaRkwpFDYzea6DsgPS9jxCZT3eL9hbebUHGLKQs9DaSFh3BBebKphv1foAYUT0Kt15BcH4tDzN7BHmPZjCH1bN5KVEd03fja2CS3JtUJt8hf8ltwYQ9jRGGDA8VKIzct0MT3XXMvZ80o3JNMQx7Wmm50=
  app: habit-trainer
  on:
    repo: habittracker/greenfield-apollo
    branch: staging
